name: ArtistMusic
options:
  deploymentTarget:
    iOS: "17.0"

targets:
  ArtistMusic:
    type: application
    platform: iOS
    sources:
      - path: Sources 
    resources: [Resources]
    settings:
      INFO_PLIST_FILE: Sources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.theo.artistmusic

